name: Update Traffic Data

on:
  push:  # Permite actualizar manualmente al hacer un push
    branches:
      - main
  schedule:  # Actualizaciones automáticas cada 5 minutos
    - cron: "*/5 * * * *"
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub Actions

jobs:
  update-traffic-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Requirements
        run: pip install requests

      - name: Run Python Script
        run: python traffic_data.py

      - name: Force Git Add
        run: git add -A

      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update traffic data" || echo "No changes to commit"

      - name: Push Changes
        run: git push
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Requirements
        run: pip install requests

      - name: Run Python Script
        run: python traffic_data.py

      - name: Force Git Add
        run: git add -A

      - name: Pull Latest Changes
        run: |
          git fetch origin main
          git merge origin/main

      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update traffic data" || echo "No changes to commit"

      - name: Push Changes
        run: git push origin main
